install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - pdflatex Example.tex
 
notifications:
  email:
    recipients:
      - hugh.parsonage+travisrepo@gmail.com
    on_success: change
    on_failure: always
    on_start:   never
