sudo: true
  
before_install:
 - sudo apt-get install -y texlive
  
install: true

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - pdflatex Example.tex
 
notifications:
  email:
    recipients:
      - hugh.parsonage+travisrepo@gmail.com
    on_success: change
    on_failure: always
    on_start:   never
