language: r

sudo: true
cache: 
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false


before_install:
  - source ./source/texlive.sh
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra
  - tlmgr biber
  - Rscript -e "if (!requireNamespace('knitr')) install.packages('knitr')"

install: echo Installation step #do not remove this line!

script: 
  - Rscript -e "knitr::knit('Example.Rnw')"
  - pdflatex -draftmode Example.tex
  - biber Example
  - pdflatex -draftmode Example.tex

after_success: tools/deploy.sh

notifications:
  email: false
