language: r

sudo: false
cache: packages
warnings_are_errors: false


before_install:
  - tlmgr install acronym chngcntr cmap nowidow mdframed navigator tablefootnote tocloft

install: echo Installation step #do not remove this line!

script: pdflatex Example.tex

after_success: tools/deploy.sh

notifications:
  email: false
